[package]
name = "worker"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.41", features = ["full"] }
tokio-util = { version = "0.7", features = ["rt"] }
